<?php
function dailyOrders(){

  $args = array(
      'limit' => '1000',
      'status' => 'processing',
      'date_created' => '>' . ( time() - DAY_IN_SECONDS )
    );
    $orders = wc_get_orders( $args );

    $date = new DateTime();
    $date->setTimezone(new DateTimeZone('America/New_York'));
    $filename = $date->format('m_d_Y').'.csv';

    $path = getcwd() .'/path/to/private/logs';

    $logFile = fopen($path.$filename, "w") or die("Unable to open file!");
    fwrite($logFile,'Woo-ID'.',WEB-ID'. ',Timestamp,' .'Export_Status' ."\n");
    foreach ($orders as $order){
      //Meta_data 2 is status on whether the 
      if($order->meta_data[2]->value == 1){
        $orderStatus = 'Exported';
      }
      else{
        $orderStatus = 'Failed_Export';
      }
      //Meta_data is defined in plugin XML Export Suite
      //meta_data[4]->value is the custom order ID generated by the plugin
      fwrite($logFile,$order->id.',WEB-'.$order->meta_data[4]->value.','.$order-> get_date_paid().','.$orderStatus."\n");
    }
    fclose($logFile);

    $to = array('someone@website.com','me@company.com');
    $subject = 'Woo ID Logs '.$date->format('m-d-Y');
    $body = 'Attached are all purchasing ids proccessed by Woocommerce';
    $headers = array('Content-Type: text/html; charset=UTF-8');
    $attachments = $path.$filename;

    wp_mail( $to, $subject, $body, $headers, $attachments );

}
?>
